name = "compatibility-playwright-express"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:go"]
enabled = false

[runners."local:docker"]
enabled = true

[[testcases]]
name = "hello"
instances = { min = 1, max = 1, default = 1 }
