name = "basic-example-playwright"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "basic"
instances = { min = 1, max = 1, default = 1 }

[[testcases]]
name = "multiple"
instances = { min = 2, max = 5, default = 2 }