[metadata]
name    = "playwright-composition-ping-pong-log-test"
author  = "glendc"

[global]
plan    = "playwright-composition-ping-pong-log-test"
builder = "docker:generic"
runner  = "local:docker"
case    = "pingpong"
total_instances = 2

[[groups]]
id = "ping"
instances = { count = 1 }

  [groups.build]

  [groups.build_config]
  path = "./ping"

  [groups.run]
  test_params = { }

[[groups]]
id = "pong"
instances = { count = 1 }

  [groups.build]

  [groups.build_config]
  path = "./pong"

  [groups.run]
  test_params = { }