name = "compatibility-nodejs"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:go"]
enabled = false

[runners."local:docker"]
enabled = true

[[testcases]]
name = "pingpong"
instances = { min = 2, max = 2, default = 2 }
